{% set name = "verticalize" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lindenb/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e8aeb3e1ce0e836aa5e47ccfe75578eb96240e5d181a78396b375bc9916d331a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - verticalize -h

about:
  home: https://github.com/lindenb/verticalize
  summary: "Simple tool to verticalize text delimited files."
  license:  MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - clintval
